import type { AiClient } from '../types.js';
import type { Article } from '../../sources/types.js';
import type { StageOutput } from './types.js';

export async function generateKnowledge(
  article: Article,
  client: AiClient,
  tone: string
): Promise<StageOutput> {
  const today = new Date().toISOString().split('T')[0];

  const primarySourceInfo = article.primarySourceUrl
    ? `一次ソース: ${article.primarySourceUrl}（種別: ${article.primarySourceType ?? 'unknown'}）`
    : '一次ソース: なし';

  const contentSection = article.content
    ? `本文:\n${article.content.slice(0, 2000)}`
    : article.summary
    ? `サマリー:\n${article.summary}`
    : '本文・サマリーなし';

  const toneInstruction = tone === 'technical'
    ? 'テクニカルな解説調で、専門用語を正確に使いながら詳しく説明してください。'
    : tone === 'casual'
    ? 'カジュアルで読みやすいトーンで、難しい用語は噛み砕いて説明してください。'
    : `${tone}のトーンで記事を作成してください。`;

  const systemPrompt = `あなたは海外AI/ML情報を正確に日本語へ翻訳・要約する技術ライターです。
${toneInstruction}

## 執筆ルール
- 原文の主張・構造を忠実に保った日本語翻訳+要約を行う
- 技術用語は正確に訳し、必要に応じ原語を併記する（例: ファインチューニング（fine-tuning））
- 元記事にコード例・設定例があればそのまま含める（なければ無理に追加しない）
- ツール名・サービス名は正式名称を省略しない
- ソース情報を明記する

以下のMarkdown構造で出力してください:

# [元記事タイトルの日本語訳]

**[元記事の要点を1文で]**

## 要約
（原文の主張を忠実に要約。2-4段落）

## キーポイント
- （重要ポイント3-5件）

## コード例・設定例
（元記事にコード例があればそのまま含める。なければこのセクションは省略）

---
## ソース
- [原題](URL) by 著者名
Generated by Mimi | ${today}`;

  const userPrompt = `以下の記事を日本語解説記事に変換してください。

タイトル: ${article.title}
URL: ${article.url}
${primarySourceInfo}
${contentSection}`;

  const content = await client.chat(systemPrompt, userPrompt);

  return {
    articleId: article.id,
    stage: 'knowledge',
    content,
  };
}
