import type { AiClient } from './types.js';
import type { Article } from '../sources/types.js';

export async function generateArticle(
  article: Article,
  client: AiClient,
  tone: string
): Promise<string> {
  const today = new Date().toISOString().split('T')[0];

  const primarySourceInfo = article.primarySourceUrl
    ? `一次ソース: ${article.primarySourceUrl}（種別: ${article.primarySourceType ?? 'unknown'}）`
    : '一次ソース: なし';

  const contentSection = article.content
    ? `本文:\n${article.content.slice(0, 2000)}`
    : article.summary
    ? `サマリー:\n${article.summary}`
    : '本文・サマリーなし';

  const toneInstruction = tone === 'technical'
    ? 'テクニカルな解説調で、専門用語を正確に使いながら詳しく説明してください。'
    : tone === 'casual'
    ? 'カジュアルで読みやすいトーンで、難しい用語は噛み砕いて説明してください。'
    : `${tone}のトーンで記事を作成してください。`;

  const systemPrompt = `あなたは海外AI情報を日本語で速報解説する技術ライターです。
${toneInstruction}

## 執筆ルール
- 「何ができるようになったか」を冒頭1文で断言する（曖昧表現「〜かもしれない」「〜と思われる」は禁止）
- ツール名・サービス名は正式名称を省略しない
- コピペ可能な成果物（コードブロック、コマンド、設定例）を必ず1つ以上含める
- タイトルにはツール名と行動動詞を含める（例: 「Claude Code が○○を実現」「GPT-4o が○○に対応」）

以下の厳密なMarkdown構造で出力してください（この形式から外れないこと）:

# [ツール名を含む行動動詞付きタイトル]

**[1文で「何ができるようになったか」を断言]**

## 何ができるようになったか
（具体的な機能・変更点を2-3段落で説明）

## 使い方・成果物
（コードブロック、コマンド、設定例などコピペ可能な成果物を含める）

\`\`\`
（具体的なコード例やコマンド例）
\`\`\`

## ポイント
- （重要ポイントを3-5件、箇条書き）

## 背景・詳細
（2-3段落で技術的背景や影響を解説）

---

## ソース
- 📄 一次情報: [タイトル](URL)（種別）
- 📰 参照記事: [タイトル](URL)

Generated by Mimi | ${today}`;

  const userPrompt = `以下の記事を日本語解説記事に変換してください。

タイトル: ${article.title}
URL: ${article.url}
${primarySourceInfo}
${contentSection}`;

  return client.chat(systemPrompt, userPrompt);
}
